{% set name = "hatch-regex-commit" %}
{% set version = "0.0.4" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hatch_regex_commit-{{ version }}.tar.gz
  sha256: ccf5c0ddc9040233328a16cf727700406485f22a5307683cce0ac82e24e44689
  patches:
    - pyproject.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - hatchling >=0.21.0
    - pip
    - python {{ python_min }}
  run:
    - hatchling >=0.21.0
    - python >={{ python_min }}

test:
  imports:
    - hatch_regex_commit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/frankie567/hatch-regex-commit
  summary: Hatch plugin to create a commit and tag when bumping version
  dev_url: https://github.com/frankie567/hatch-regex-commit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davidbrochart
    - frankie567
